
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "v1.2.1"

[[constraint]]
  name = "github.com/hsluv/hsluv-go"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/omniscale/go-mapnik"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

[[constraint]]
  branch = "release-branch.go1.8"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/natefinch/pie"
  version = "v1.0"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.2"
